---
ID: "425e5f3b-4a13-4898-8684-cbdb81818efb"
Parent: "50c05701-4b87-412a-9652-fda884887b4d"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/Nishtech/NXA-Headless/Nishtechwww/Settings/Shared Sites Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230526T151230Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f15bce8d-caa2-477a-bc19-b1925381eab5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230526T151230Z
