---
ID: "d0ba33ff-dac3-4adc-9ece-fa8ff96cc522"
Parent: "50c05701-4b87-412a-9652-fda884887b4d"
Template: "ab987746-78b0-4773-a8de-b295c493b7a4"
Path: "/sitecore/content/Nishtech/NXA-Headless/Nishtechwww/Settings/Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230526T151229Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "91614a87-27fd-4745-b411-4369ba0f88f8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230526T151229Z
