---
ID: "8b4dfe22-dd8b-4f1a-a233-006c8c2b1e07"
Parent: "ab770dfd-fcf8-49b4-aef4-9f3e404bbbca"
Template: "ab770dfd-fcf8-49b4-aef4-9f3e404bbbca"
Path: "/sitecore/templates/Project/Nishtech/NXA-Headless/JSS Settings/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230526T151206Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "641493fa-d317-4b3a-aed6-9aef3987092b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230526T151206Z
